version: '3.8'

services:
  object-storage:
    image: quay.io/minio/minio
    ports:
      - "65300:9000"
      - "65301:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./miniio_data:/data
    command: server /data --console-address ":9001"

  database:
    image: surrealdb/surrealdb:latest
    ports:
      - "65303:8000"
    user: "1000"
    volumes:
      - ./database:/horus_database
    command: start --user root --pass root rocksdb:/horus_database/horus_database.db

  horus-ffmpeg-server:
      build:
        context: .
        dockerfile: docker/Dockerfile.ffmpeg
      image: horus_ffmpeg_server:latest
      depends_on:
        - object-storage 
        - database
      ports:
        - "65302:8000"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu, video]
      command: uvicorn ffmpeg_server_api:app --host 0.0.0.0 --port 8000

  horus-backend-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: horus_backend_server:latest
    depends_on:
      - object-storage 
      - database
    ports:
      - "65304:8000"
    volumes:
      - ./src:/workspace/src
    command: /bin/bash -c "while true; do sleep 1000; done"
    stdin_open: true
    tty: true
