FROM nvcr.io/nvidia/tensorrt:23.01-py3

WORKDIR /workspace

RUN python3 -m pip install -U pip && \
    python3 -m pip install \
        torch==2.4.1 \
        torchvision==0.19.1 \
        faster-coco-eval==1.6.7 \
        PyYAML==6.0.2 \
        tensorboard==2.14.0 \
        scipy==1.10.1 \
        pycocotools==2.0.7 \
        onnx==1.17.0 \
        onnxruntime-gpu==1.19.2 \
        tensorrt==8.5.2.2