FROM ubuntu:jammy

RUN apt update && apt install -y \
    python3 \
    python3-pip \
    git \
    curl

RUN python3 -m pip install -U pip && \
    python3 -m pip install -U \
    fastapi==0.115.13 \
    uvicorn==0.34.3 \
    requests==2.32.3 \
    surrealdb==1.0.4 \
    boto3==1.38.44 \
    python-multipart

WORKDIR /workspace
